services:
    app:
        build: .
        ports:
            - "3000:3000"
        # depends_on:
        #     - db
        environment:
            DB_HOST: host.docker.internal
            DB_PORT: 5432
        extra_hosts:
            - "host.docker.internal:host-gateway"
    # db:
    #     image: postgres
    #     environment:
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres
    #         POSTGRES_DB: postgres
    #     restart: always
    #     volumes:
    # - .\a-postgre-init-db.sh:/docker-entrypoint-initdb.d/a-postgre-init-db.sh
    # - E:\Download\kesehatan.sql:/docker-entrypoint-initdb.d/kesehatan.sql
    # - type: volume
    #   source: mydata
    #   target: /var/lib/postgresql/data
    # - type: tmpfs
    #   target: /dev/shm
    #   tmpfs:
    #   size: 134217728 # 128*2^20 bytes = 128Mb
    # ports:
    #     - "5432:5432"
    # command: ["postgres", "-c", "listen_addresses=*"]
    # shm_size: "2gb"
    # networks:
    #     - sonic-network
    # pgadmin:
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: admin@admin.comm
    #         PGADMIN_DEFAULT_PASSWORD: admin
    #     ports:
    #         - "5050:8081"
# networks:
#     default:
#         driver: bridge
volumes:
    mydata:
