import { config } from "dotenv";

config();

export const Encounter_id = "";
export const OrganizationID = process.env.ORG_ID;
export const Registration_ID = "ABC123";
export const Patient_Id = "P02478375538";
export const Patient_Name = "Ardianto Putra";
export const Practitioner_Id = "10009880728";
export const Practitioner_Name = "dr. Alexander";
export const Condition_DiagnosisPrimer = "";
export const Condition_DiagnosisSekunder = "";
export const Location_Ruang210_Bed2_id = "";
export const CarePlan_RencanaRawat_id = "";
export const Observation_Kesadaran = "";
export const Observation_Nadi = "";
export const CarePlan_Instruksi = "";
export const Procedure_PraLab = "";
export const ServiceRequest_Lab = "";
export const Specimen_Lab = "";
export const Observation_Lab = "";
export const DiagnosticReport_Lab = "";
export const Procedure_Hemodialisis = "";
export const Medication_forRequest1 = "";
export const Medication_forRequest2 = "";
export const Medication_forRequest3 = "";
export const MedicationRequest_id1 = "";
export const MedicationRequest_id2 = "";
export const MedicationRequest_id3 = "";
export const QuestionnaireResponse_KajianResep = "";
export const Medication_forDispense1 = "";
export const Medication_forDispense2 = "";
export const Medication_forDispense3 = "";
export const MedicationDispense_id1 = "";
export const MedicationDispense_id2 = "";
export const MedicationDispense_id3 = "";
export const Procedure_Edukasi = "";
export const Observation_RencanaPulang = "";
export const CarePlan_RencanaPulang = "";
export const ClinicalImpression_Prognosis = "";
export const ServiceRequest_Kontrol = "";
export const Condition_Stabil = "";
export const Practitioner_Lab_Id = "";
export const Practitioner_Apoteker_Id = "";
